export const defaultCopilotState = {
  last_intent: null,
  last_entities: {},
  selected_student_id: null,
  selected_course_id: null,
  selected_class_id: null,
  last_selected_student: null,
  last_selected_course: null,
  last_selected_class: null,
  last_created_student: null,
  last_found_student: null,
  last_created_course: null,
  last_created_class: null,
  last_candidates: {
    students: [],
    courses: [],
    classes: [],
  },
  pending_action: null,
  pending_course_confirmation: null,
  pending_clarification: null,
  duplicate_student_context: null,
  current_focus: null,
  last_suggestions: [],
  last_suggestion_source: null,
};
